on: 
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test Env tags'  


jobs:
    example-job:
      steps:
        - name: Retrieve secret
          env:
            c8y_user: ${{ secrets.C8Y_USER }}
          run: |
            echo "$c8y_user"
